### ISSUE TITLE
Fazer cadastro Currículo Lattes

### ISSUE THREAD

**Issue by lucileidedantas** [IFRN-SC/Megazords#25]
Fazer o currículo na plataforma Lattes.

Segue o link: http://lattes.cnpq.br/ (Abrir menu: Cadastrar novo currículo - Menu lateral à direita).

Precisamos que vocês se cadastrem nessa plataforma para poder cadastrar vocês em projetos no SUAP e até em alguns eventos.

**Comment by MirosmarJoseph19** [comment]
http://lattes.cnpq.br/5660787449829447
O link do meu cadastro.

**Comment by HenriqueEduardo1** [comment]
Bruna já fez
